variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala:
  script:
    - "$CI_SCRIPTS_DIR/test-mac.sh"
  tags:
    - gift-gala
    - gift-mac
    - java

gift-adelie:
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-adelie
    - gift-linux
    - java
  except:
	- dev  

gift-adelie-deploy:
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
    - "$CI_SCRIPTS_DIR/test-and-deploy-linux.sh"
  tags:
    - gift-adelie
    - gift-linux
    - java
  only:
	- dev  		

gift-jalousie:
  script:
    - "call .\\ci\\test-win.bat"
  tags:
    - gift-jalousie
    - gift-win
    - gift-win10
    - java

gift-skylight:
  script:
    - "call .\\ci\\test-win.bat"
  tags:
    - gift-skylight
    - gift-win
    - gift-win10
    - java
