variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala:
  script:
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-gala
    - gift-mac

gift-adelie:
  script:
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-adelie
    - gift-linux

gift-gala-win:
  script:
    - "%CI_SCRIPTS_DIR%\test-win.bat"
  tags:
    - gift-win

