variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala:
  script:
    - "$CI_SCRIPTS_DIR/test-mac.sh"
  tags:
    - gift-gala
    - gift-mac
    - java

gift-adelie-test-and-package:
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
    - "$CI_SCRIPTS_DIR/test-and-package-linux.sh"
  tags:
    - gift-adelie
    - gift-linux
    - java
  except:
    - dev  
    - master  

gift-adelie-deploy-testserver:
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
    - "$CI_SCRIPTS_DIR/test-and-deploy-linux.sh"
  tags:
    - gift-adelie
    - gift-linux
    - java
  only:
    - dev

gift-adelie-deploy-master:
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
    - "$CI_SCRIPTS_DIR/test-and-build-release-linux.sh"
    - "$CI_SCRIPTS_DIR/deploy-docs.sh"
  tags:
    - gift-adelie
    - gift-linux
    - java
  only:
    - master  		

gift-skylight:
  script:
    - "call .\\ci\\test-win.bat"
  tags:
    - gift-skylight
    - gift-win
    - gift-win10
    - java
