variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala:
  script:
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-gala
    - gift-mac
	- java

gift-adelie:
  script:
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-adelie
    - gift-linux
	- java

gift-jalousie:
  script:
    - "call .\\ci\\test-win.bat"
  tags:
	- gift-jalousie
    - gift-win
	- java

