variables:
  HOME_DIR: "/home/gitlab-runner"

before_script:
  - export SCRATCH_DIR="$(pwd)/../scratch-space"

gift-gala:
  script:
    - touch ~/runner_start.txt 
    - mvn install -B
    - touch ~/runner_done.txt 
  tags:
    - gift-gala